name: CI-CD for Wistia Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-2
      LAMBDA_FUNCTION_NAME: wistia_ingestion_function
      GLUE_SCRIPT_S3_BUCKET: aws-glue-assets-572318586627-us-east-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::572318586627:role/github-actions-wistia-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Confirm AWS identity
        run: aws sts get-caller-identity

      - name: Deploy Lambda
        run: |
          cd lambda
          zip -r function.zip wistia-ingestion-function.py
          aws lambda update-function-code \
            --function-name "$LAMBDA_FUNCTION_NAME" \
            --zip-file fileb://function.zip

      - name: Upload all Glue script to S3
        run: |
          aws s3 sync glue/ s3://$GLUE_SCRIPT_S3_BUCKET/scripts/
